"""Adicionar campo reserva à tabela Alimento

Revision ID: 81f78f42919d
Revises: 
Create Date: 2024-01-20 14:26:53.526719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81f78f42919d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alimento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reserva', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alimento', schema=None) as batch_op:
        batch_op.drop_column('reserva')

    # ### end Alembic commands ###
